# Site settings
title: Jxqt Blog
SEOTitle: ä»Šæ˜ŸæœŸå¤©çš„åšå®¢ | Jxqt Blog
# header-img: 
email: zjkgf@163.com
description: "å…³äºç¨‹åºä¸è®¾è®¡ã€é»‘å®¢ä¸ç”»å®¶ | é»„ç„ï¼ŒWeb & Mobile Loverï¼ŒSoftware Engineerï¼ŒUX Designer | è¿™é‡Œæ˜¯ @Huxé»„ç„ çš„ä¸ªäººåšå®¢ï¼Œä¸ä½ ä¸€èµ·å‘ç°æ›´å¤§çš„ä¸–ç•Œã€‚"
keyword: "ä»Šæ˜ŸæœŸå¤©, æ˜ŸæœŸå¤©, Jxqt, å‘¨å¤©, ç¤¼æ‹œå¤©, @å‘¨æ—¥, ä»Šæ˜ŸæœŸå¤©çš„åšå®¢, jxqt Blog, åšå®¢, ä¸ªäººç½‘ç«™, äº’è”ç½‘, Web, JavaScript, å‰ç«¯, è®¾è®¡"
url: "https://jxqt.github.io"              # your host, for absolute URL
# baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false


Build settings:      3
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
# permalink: pretty
paginate: 10
# ä¸‹é¢ğŸ‘‡ä¸åŒ…æ‹¬ä¸­æ‹¬å·é‡Œçš„å†…å®¹
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
# ğŸ‘‡ anchor.js æ˜¯ç®€å•ä¸”æœ‰ç”¨çš„ jQuery æ’ä»¶ï¼Œä¸ºæ‰€æœ‰æœ¬åœ°é“¾æ¥æä¾›ä¸€ä¸ªå¹³æ»‘çš„åŠ¨ç”»ï¼Œç„¶åè·³è½¬åˆ°é¡µé¢çš„ä»»æ„ä¸€ä¸ªå…ƒç´ 
anchorjs: false                          
# if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN  





# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# gems: [jekyll-paginate]
# ä¸‹é¢è¡ŒğŸ‘‡ä¸ºåˆ†é¡µæ’ä»¶
plugins: [jekyll-paginate]


# ä¸‹é¢ğŸ‘‡ä¸ºè½»é‡çº§ç¼–è¾‘è¯­è¨€è®¾ç½®
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                           
# use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
# sidebar-about-description: "For the next quantum leap<br>ç¦»å¼€ä¸–ç•Œä¹‹å‰ï¼Œä¸€åˆ‡éƒ½æ˜¯è¿‡ç¨‹"
# sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# ğŸ‘‡ æ¼¸é€²å¼ç¶²è·¯æ‡‰ç”¨ç¨‹å¼æ˜¯ä¸€ç¨®æ™®é€šç¶²é æˆ–ç¶²ç«™æ¶æ§‹èµ·ä¾†çš„ç¶²è·¯æ‡‰ç”¨ç¨‹å¼ï¼Œä½†å®ƒå¯ä»¥ä»¥å‚³çµ±æ‡‰ç”¨ç¨‹å¼æˆ–åŸç”Ÿè¡Œå‹•æ‡‰ç”¨ç¨‹å¼å½¢å¼å±•ç¤ºçµ¦ä½¿ç”¨è€…ã€‚é€™ç¨®æ‡‰ç”¨ç¨‹å¼å½¢æ…‹è¦–åœ–å°‡ç›®å‰æœ€ç‚ºç¾ä»£åŒ–çš„ç€è¦½å™¨æä¾›çš„åŠŸèƒ½èˆ‡è¡Œå‹•è£ç½®çš„é«”é©—å„ªå‹¢ç›¸çµåˆã€‚
# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
# MathJaxæ˜¯ä¸€å€‹è·¨ç€è¦½å™¨çš„JavaScript ç¨‹å¼åº«ï¼Œå®ƒä½¿ç”¨MathMLã€LaTeXå’ŒASCIIMathMLæ¨™è¨˜åœ¨Webç€è¦½å™¨ä¸­é¡¯ç¤ºæ•¸å­¸ç¬¦è™Ÿã€‚MathJaxæ˜¯åœ¨Apacheæˆæ¬Šæ¢æ¬¾ä¸‹ä½œç‚ºé–‹æºè»Ÿé«”ç™¼å¸ƒçš„ã€‚
page-mathjax: false



# Friends
friends: [
    {
      title: "è–°è¡£è‰ï¼Œæ´‹",
      href: "https://v.kuaishou.com/zHs3qD"
    },{
      title: "wpys168",
      href: "http://sj.ysupan.com/zjkgf"
    },{
        title: "k1314",
        href: "https://v.kuaishou.com/xgauhm"
    },{
        title: "ç´å¦¹427774279",
        href: "https://v.kuaishou.com/z1HiAI"
    },{
        title: "éŸ©å¥³å›¢ba",
        href: "https://v.kuaishou.com/Bj0WcX"
    },{
        title: "å¾®ä¿¡ajtdjt",
        href: "https://v.kuaishou.com/zXmkKl"
    },{
        title: "å—æ–¹æ³µä¸š",
        href: "https://ksirq.github.io/"
    },{
        title: "å¹³é‚‘é˜²æ°´",
        href: "https://rsxj.github.io/"
    },{
        title: "GitHub",
        href: "https://www.github.com/"
    },{
        title: "Jxqt",
        href: "https://jxqt.github.io/"
    },{
        title: "google mail",
        href: "https://mail.google.com"
    },{
        title: "gitå†™åš",
        href: "https://github.com/jxqt/jxqt.github.io/tree/master/_posts"
    } ,{
        title: "æ¢å±±ç«‹é¸¿äºŒæ‰‹è®¾å¤‡ä¹°å–",
        href: "https://v.kuaishou.com/zRZMUU"
    }


]

theme: jekyll-theme-cayman
