# Site settings
title: Jxqt Blog
SEOTitle: 今星期天的博客 | Jxqt Blog
# header-img: 
email: zjkgf@163.com
description: "今星期天, 星期天, Jxqt, 周天, 礼拜天, @周日, 今星期天的博客, jxqt Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
keyword: "今星期天, 星期天, Jxqt, 周天, 礼拜天, @周日, 今星期天的博客, jxqt Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://jxqt.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          
# if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN  





# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                           
# use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
# sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
# sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false




# Friends
friends: [
    {
      title: "抖音去水印",
      href: "https://3g.gljlw.com/diy/douyin.php"
    },{
      title: "永顺e盘",
      href: "http://sj.ysupan.com/zjkgf"
    },{
        title: "k1314",
        href: "https://v.kuaishou.com/xgauhm"
    },{
        title: "琴妹427774279",
        href: "https://v.kuaishou.com/z1HiAI"
    },{
        title: "快手me",
        href: "https://v.kuaishou.com/MbEOYz%20%E7%9C%8B%E4%BA%86%E8%BF%99%E4%B9%88%E5%A4%9A%E5%BF%AB%E6%89%8B%EF%BC%8C%E8%BF%98%E6%98%AF%E3%80%8C%E4%BC%97%E5%85%AC-%E9%9A%8F%E6%84%8F%E9%AC%BC-%E5%8F%B7%E3%80%8D%E6%9C%80%E5%A5%BD%E7%8E%A9%E4%BA%86%EF%BC%81%20%E5%A4%8D%E5%88%B6%E6%AD%A4%E6%B6%88%E6%81%AF%EF%BC%8C%E6%89%93%E5%BC%80%E3%80%90%E5%BF%AB%E6%89%8B%E6%9E%81%E9%80%9F%E7%89%88%E3%80%91%E7%9B%B4%E6%8E%A5%E8%A7%82%E7%9C%8B%EF%BC%81"
    },{
        title: "微信ajtdjt",
        href: "https://v.kuaishou.com/zXmkKl"
    },{
        title: "南方泵业",
        href: "https://ksirq.github.io/"
    },{
        title: "平邑防水",
        href: "https://rsxj.github.io/"
    },{
        title: "GitHub",
        href: "https://www.github.com/"
    },{
        title: "Jxqt",
        href: "https://jxqt.github.io/"
    },{
        title: "google mail",
        href: "https://mail.google.com"
    },{
        title: "git写博",
        href: "https://github.com/jxqt/jxqt.github.io/tree/master/_posts"
    } ,{
        title: "梁山立鸿二手设备买卖",
        href: "https://v.kuaishou.com/zRZMUU"
    } ,{
        title: "My YouTube ",
        href: "https://youtube.com/channel/UCUZwShKs5wKXvwFdLTseI9A"
    },{
        title: "微信号ajtdjt ",
        href: ""
    } ,{
        title: "草料网",
        href: "https://cli.im/tools"
    } ,{
        title: "图片压缩",
        href: "https://yasuo.xunjiepdf.com/img/"
    } ,{
        title: "视频解析",
        href: "https://youtube.iiilab.com/"
    } 


]

theme: jekyll-theme-cayman
